### ISSUE TITLE
Tamaños iconos

### ISSUE THREAD

**Issue by gusanchez** [gusanchez/Flyermob#10]
Enviar los tamaños que se necesitan para los iconos, logos e imagenes

**Comment by robtoes** [comment]
Los tamaños requeridos son los siguientes.

Iconos: 192x192 px
formato: PNG 32Bits.

Imagenes:
SplashScreen: 1200x1200 px.
Logo: 360x200px
Imagenes: pueden tener de ancho (width) 480px. 
Promos: 300x170 px

**Comment by gusanchez** [comment]
Dimensiones mínimas y máximas para:
- Botones
- Iconos
- Imágenes:
  - Fondos
  - Splash
  - Promos
- Fotos de perfil
- Launcher

Formato: PNG 32 Bits
Dpi: alguna limitación?

Wiki del look and feel https://bitbucket.org/octagonweb/octagon_web/wiki/FlyerMob

**Comment by robtoes** [comment]
**Botones**: Seria mejor que los botones tengan un color y un icono asociado (si lo piden asi) para que la app no este tan recargada de imagenes que solo se usaran una vez.
**Fotos de perfil**: 192x192px
**Imagenes**:
- **Fondos**: puede ser un color fijo, en ese caso indicar el codigo RGB, y si se quiere una imagen se puede realizar un patron con una imagen cuadrada de 40x40px o similar.
- **Splash**: 1200x1200px
- **Iconos**: pueden ser de 48x48 px. Si son muy pequeños se los indicaria.

**Launcher**: 98x98 px.

Los iconos pueden ser en 32 Bits para usar el alfa channel.

Los DPI se usarian para el manejo de los elementos internos de la pantalla, ej, botones, listas, imagenes. No sabria decir si se pueden usar DPI en las magenes. Creo que en ese caso las imagenes deberia ser vectoriales.
